<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Contenido',
    'Entity' => 'Entidad',
    'Entity ID' => 'ID Entidad',
    'Parent ID' => 'Parent ID',
    'Status' => 'Estado',
    'Level' => 'Nivel',
    'Created by' => 'Creado por',
    'Updated by' => 'Actualizado por',
    'Related to' => 'Relacionado con',
    'Url' => 'Url',
    'Created date' => 'Created date',
    'Updated date' => 'Updated date',
    'View' => 'View',
    'Update' => 'Actualizar',
    'Delete' => 'Borrar',
    'Reply' => 'Responder',
    'Comments ({0})' => 'Comentarios ({0})',
    '{0} Comments' => '{0} Comentarios',
    'Comment cannot be blank.' => 'El comentario no puede estar vacio.',
    'Comment has not been deleted. Please try again!' => 'El comentario no ha sido borrado. ¡Intentelo de nuevo!',
    'Add a comment...' => 'Añade un comentario...',
    'Comment' => 'Comenta',
    'Oops, something went wrong. Please try again later.' => 'Oops, algo fue mal. Por favor intentelo de nuevo mas tarde.',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Comment has been deleted.' => 'El comentario ha sido eliminado.',
    'Comment has been saved.' => 'El comentario ha sido guardado.',
    'Click here to cancel reply.' => 'Pulsa aqui para cancelar la respuesta.',
    'Comments Management' => 'Comments Management',
    'Select Status' => 'Select Status',
    'Select Author' => 'Select Author',
    'Update Comment: {0}' => 'Actualizar Comentario: {0}',
    'Active' => 'Activo',
    'Deleted' => 'Borrado',
    'Go Back' => 'Vuelve atrás',
];
